### ISSUE TITLE
Shall we add a travis build for this repo?

### ISSUE THREAD

**Issue by cdwijayarathna** [wso2-extensions/identity-inbound-provisioning-scim2#54]

**Comment by mefarazath** [comment]
+1

**Comment by cdwijayarathna** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/56

**Comment by mefarazath** [comment]
Closing this issue since travis CI is enabled for all active branches of this repo successfully :smiley:
